# Generated by Django 4.2.1 on 2023-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperPrensarank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('urls_site', models.CharField(max_length=50, verbose_name='url del sitio')),
                ('dr', models.CharField(max_length=3, verbose_name='DR')),
                ('da', models.CharField(max_length=3, verbose_name='DA')),
                ('cf', models.CharField(max_length=3, verbose_name='CF')),
                ('tf', models.CharField(max_length=3, verbose_name='TF')),
                ('traffic', models.CharField(max_length=9, verbose_name='Tráfico')),
                ('price', models.CharField(max_length=7, verbose_name='Precio')),
                ('max_links', models.CharField(max_length=6, verbose_name='Links máximos')),
                ('max_links_groups', models.CharField(max_length=6, verbose_name='Links Máximos de grupos')),
            ],
            options={
                'verbose_name': 'Prensarank',
                'verbose_name_plural': 'Prensaranks',
            },
        ),
    ]
