# Generated by Django 4.2.1 on 2023-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperPrensarank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('country', models.CharField(default='sin país', max_length=25, verbose_name='País')),
                ('tipo', models.CharField(default='web', max_length=15, verbose_name='Tipo')),
                ('dr', models.CharField(max_length=3, verbose_name='DR')),
                ('da', models.CharField(max_length=3, verbose_name='DA')),
                ('cf', models.CharField(max_length=3, verbose_name='CF')),
                ('tf', models.CharField(max_length=3, verbose_name='TF')),
                ('traffic', models.CharField(max_length=9, verbose_name='Tráfico')),
                ('price', models.CharField(max_length=7, verbose_name='Precio')),
                ('max_links', models.CharField(max_length=6, verbose_name='Links máximos')),
                ('max_links_groups', models.CharField(max_length=6, verbose_name='Links Máximos de grupos')),
            ],
            options={
                'verbose_name': 'Prensarank',
                'verbose_name_plural': 'Prensaranks',
            },
        ),
        migrations.AddConstraint(
            model_name='scraperprensarank',
            constraint=models.UniqueConstraint(fields=('url',), name='constraint_unico_url'),
        ),
    ]
