# Generated by Django 4.2.1 on 2023-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperprensarank', '0002_alter_scraperprensarank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperprensarank',
            name='urls_site',
        ),
    ]
