# Generated by Django 4.2.1 on 2023-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperprensarank', '0004_scraperprensarank_country_scraperprensarank_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperprensarank',
            name='url',
            field=models.CharField(max_length=50, unique=True, verbose_name='URL'),
        ),
        migrations.AddConstraint(
            model_name='scraperprensarank',
            constraint=models.UniqueConstraint(fields=('url',), name='constraint_unico_url'),
        ),
    ]
