# Generated by Django 4.2.1 on 2023-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0005_remove_scraperteblogueo_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperteblogueo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='scraperteblogueo',
            old_name='url',
            new_name='url_link',
        ),
        migrations.AddField(
            model_name='scraperteblogueo',
            name='link_type',
            field=models.CharField(blank=True, null=True, verbose_name='link_type'),
        ),
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='trust_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='Trust Flow'),
        ),
    ]
