# Generated by Django 4.2.1 on 2023-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0008_remove_scraperteblogueo_link_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='name',
            field=models.CharField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='url',
            field=models.CharField(verbose_name='url'),
        ),
    ]
