# Generated by Django 4.2.1 on 2023-09-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0010_alter_scraperteblogueo_max_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='visits_month',
            field=models.FloatField(blank=True, null=True, verbose_name='visits_month'),
        ),
    ]
