# Generated by Django 4.2.1 on 2023-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0004_alter_scraperconexoo_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='descripcion'),
        ),
    ]
