# Generated by Django 4.2.1 on 2023-09-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0005_alter_scraperconexoo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='descripcion',
            field=models.CharField(verbose_name='descripcion'),
        ),
    ]
