# Generated by Django 4.2.1 on 2023-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0008_alter_scraperconexoo_tematicas_no_aceptadas_arr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='precio_post',
            field=models.CharField(max_length=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='scraperconexoo',
            name='precio_post_cliente',
            field=models.CharField(default=0, max_length=10, verbose_name='precio_post_cliente'),
        ),
    ]
