# Generated by Django 4.2.1 on 2023-06-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='slig',
            new_name='slug',
        ),
    ]
