# Generated by Django 4.2.1 on 2023-09-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0002_scraperconexoo_max_links_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperconexoo',
            name='clase_web_tex',
        ),
        migrations.AddField(
            model_name='scraperconexoo',
            name='clase_web_text',
            field=models.CharField(max_length=15, null=True, verbose_name='clase'),
        ),
    ]
