# Generated by Django 4.2.1 on 2023-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0007_alter_scraperconexoo_tipo_sitio_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='tematicas_no_aceptadas_arr',
            field=models.CharField(verbose_name='tematicas_prohibidas'),
        ),
    ]
