# Generated by Django 4.2.1 on 2023-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0009_alter_scraperconexoo_precio_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='da',
            field=models.IntegerField(null=True, verbose_name='DA'),
        ),
    ]
