# Generated by Django 4.2.1 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperTeblogueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('url', models.CharField(verbose_name='url_link')),
                ('DR', models.CharField(default=0, max_length=3, verbose_name='DR')),
                ('DA', models.FloatField(default=0, verbose_name='DA')),
                ('PA', models.FloatField(default=0, verbose_name='PA')),
                ('trust_flow', models.FloatField(verbose_name='Trust Flow')),
                ('visits_month', models.FloatField(verbose_name='Tráfico')),
                ('peffer_pvp', models.FloatField(verbose_name='peffer_pvp')),
                ('ppvp', models.FloatField(verbose_name='ppvp')),
                ('max_links', models.FloatField(verbose_name='max_links')),
                ('sponsored_mark', models.BooleanField(verbose_name='sponsored_mark')),
                ('model', models.CharField(verbose_name='model')),
            ],
            options={
                'verbose_name': 'Teblogueo',
                'verbose_name_plural': 'Area Teblogueo',
            },
        ),
    ]
