# Generated by Django 4.2.1 on 2023-09-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='DA',
        ),
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='DR',
        ),
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='PA',
        ),
    ]
