# Generated by Django 4.2.1 on 2023-09-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0002_remove_scraperteblogueo_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='visits_month',
            field=models.FloatField(default=0, verbose_name='Tráfico'),
        ),
    ]
