# Generated by Django 4.2.1 on 2023-09-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0003_alter_scraperteblogueo_visits_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperteblogueo',
            name='link_type',
            field=models.CharField(blank=True, null=True, verbose_name='link_type'),
        ),
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='visits_month',
            field=models.FloatField(blank=True, null=True, verbose_name='Tráfico'),
        ),
    ]
