# Generated by Django 4.2.1 on 2023-09-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0004_scraperteblogueo_link_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='link_type',
        ),
    ]
