# Generated by Django 4.2.1 on 2023-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0006_rename_name_scraperteblogueo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperteblogueo',
            name='nombre',
            field=models.CharField(verbose_name='nombre'),
        ),
    ]
