# Generated by Django 4.2.1 on 2023-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperteblogueo', '0007_alter_scraperteblogueo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='scraperteblogueo',
            name='url_link',
        ),
        migrations.AddField(
            model_name='scraperteblogueo',
            name='name',
            field=models.CharField(default='Sin Nombre', verbose_name='name'),
        ),
        migrations.AddField(
            model_name='scraperteblogueo',
            name='url',
            field=models.CharField(blank=True, verbose_name='url'),
        ),
    ]
