# Generated by Django 4.2.1 on 2023-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperprensarank', '0003_remove_scraperprensarank_urls_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperprensarank',
            name='country',
            field=models.CharField(default='sin país', max_length=25, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='scraperprensarank',
            name='tipo',
            field=models.CharField(default='web', max_length=15, verbose_name='Tipo'),
        ),
    ]
