# Generated by Django 4.2.1 on 2023-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scraperConexoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('url_link', models.CharField(max_length=75, verbose_name='url_link')),
                ('descripcion', models.CharField(verbose_name='descripcion')),
                ('idioma', models.CharField(max_length=10, verbose_name='idioma')),
                ('pais_audiencia', models.CharField(max_length=10, verbose_name='pais_audiencia')),
                ('da', models.IntegerField(null=True, verbose_name='DA')),
                ('precio_post', models.CharField(max_length=10, verbose_name='precio')),
                ('precio_post_cliente', models.CharField(default=0, max_length=10, verbose_name='precio_post_cliente')),
                ('max_links_post', models.CharField(max_length=3, null=True, verbose_name='max_links_post')),
                ('tipo_sitio', models.CharField(max_length=15, verbose_name='tipo')),
                ('tipo_sitio_text', models.CharField(null=True, verbose_name='tipo_sitio_text')),
                ('traffic_organic', models.FloatField(verbose_name='trafico')),
                ('clase_web_text', models.CharField(max_length=15, null=True, verbose_name='clase')),
                ('tematicas_no_aceptadas_arr', models.CharField(verbose_name='tematicas_prohibidas')),
            ],
            options={
                'verbose_name': 'Conexoo',
                'verbose_name_plural': 'Conexoos',
            },
        ),
    ]
