# Generated by Django 4.2.1 on 2023-09-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconexoo',
            name='max_links_post',
            field=models.CharField(max_length=3, null=True, verbose_name='max_links_post'),
        ),
        migrations.AddField(
            model_name='scraperconexoo',
            name='precio_post_cliente',
            field=models.CharField(default=0, max_length=5, verbose_name='precio_post_cliente'),
        ),
        migrations.AddField(
            model_name='scraperconexoo',
            name='tipo_sitio_text',
            field=models.CharField(max_length=25, null=True, verbose_name='tipo_sitio_text'),
        ),
        migrations.AlterField(
            model_name='scraperconexoo',
            name='clase_web_tex',
            field=models.CharField(null=True, verbose_name='clase'),
        ),
    ]
