# Generated by Django 4.2.1 on 2023-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperconexoo', '0003_remove_scraperconexoo_clase_web_tex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconexoo',
            name='url_link',
            field=models.CharField(max_length=75, verbose_name='url_link'),
        ),
    ]
