# Generated by Django 4.2.1 on 2023-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_rename_slig_entry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
